### ISSUE TITLE
How to run the plugin with docker compose ?

### ISSUE THREAD

**Issue by ahmed-bhs** [PetroKostyuk/adminer-tree-view#1]
Hello there, I'm loocking for a solution to enable the plugin under a docker container, I already tried this docker compose yaml, but still getting "Unable to find plugin file "'ttree-view""
```
    adminer:
        image: 'adminer:latest'
        ports:
            - '8084:8080'
        environment:
            - ADMINER_PLUGINS=tree-view
        networks:
```
Cheers!
